spring.application.name=server-monitoring

spring.datasource.url=jdbc:mysql://localhost:3306/server_monitoring?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=${YOUR_MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA가 테이블을 자동으로 만들거나 수정하지 않게 한다.
spring.jpa.hibernate.ddl-auto=none